pipeline {
    agent any
    stages {
       stage('Clone') {
            steps {
                git branch: 'main', url: 'https://github.com/DuyTC1811/jenkins-pipeline.git'
            }
       }
    }
}
